-----------------------------
-- SET OPERATORS
-----------------------------

SELECT *
FROM EMPLOYEE
WHERE EMP_ID>4
UNION
SELECT * 
FROM EMPLOYEE
WHERE MONTHLY_SALARY>3000;

SELECT *
FROM EMPLOYEE
WHERE EMP_ID>4
UNION ALL
SELECT * 
FROM EMPLOYEE
WHERE MONTHLY_SALARY>3000;

SELECT *
FROM EMPLOYEE
WHERE EMP_ID>4
INTERSECT
SELECT * 
FROM EMPLOYEE
WHERE MONTHLY_SALARY>3000;

SELECT *
FROM EMPLOYEE
WHERE EMP_ID>4
MINUS
SELECT * 
FROM EMPLOYEE
WHERE MONTHLY_SALARY>3000;


------------------------------------
-- WORKING WITH JOINS
------------------------------------
/*
    SELECT [COLUMN NAMES]
    FROM [LEFT TABLE]
    [FULL/LEFT/RIGHT] JOIN [RIGHT TABLE]
    ON [JOIN CONDITION]
*/

-- INNER JOIN
SELECT EMPLOYEE.EMP_NAME, DEPARTMENT.DEPT_NAME
FROM EMPLOYEE
JOIN DEPARTMENT
ON EMPLOYEE.DEPT_ID = DEPARTMENT.DEPT_ID;

-- COLUMN ALIAS
SELECT EMPLOYEE.EMP_NAME AS NAME, DEPARTMENT.DEPT_NAME AS DEPARTMENT 
FROM EMPLOYEE
JOIN DEPARTMENT
ON EMPLOYEE.DEPT_ID = DEPARTMENT.DEPT_ID;

-- COLUMN ALIAS
SELECT E.EMP_NAME AS NAME, D.DEPT_NAME AS DEPARTMENT 
FROM EMPLOYEE E
JOIN DEPARTMENT D
ON E.DEPT_ID = D.DEPT_ID;

-- IMPLICIT INNER JOIN
SELECT E.EMP_NAME AS NAME, D.DEPT_NAME AS DEPARTMENT
FROM EMPLOYEE E, DEPARTMENT D
WHERE E.DEPT_ID = D.DEPT_ID;

-- FULL (OUTER) JOIN
SELECT E.EMP_NAME AS NAME, D.DEPT_NAME AS DEPARTMENT
FROM EMPLOYEE E
FULL JOIN DEPARTMENT D
ON E.DEPT_ID = D.DEPT_ID;

-- LEFT JOIN 
SELECT E.EMP_NAME AS NAME, D.DEPT_NAME AS DEPARTMENT
FROM EMPLOYEE E
LEFT JOIN DEPARTMENT D
ON E.DEPT_ID = D.DEPT_ID;

-- RIGHT JOIN
SELECT E.EMP_NAME AS NAME, D.DEPT_NAME AS DEPARTMENT
FROM EMPLOYEE E
RIGHT JOIN DEPARTMENT D
ON E.DEPT_ID = D.DEPT_ID;

-- CROSS JOIN
SELECT E.EMP_NAME AS NAME, D.DEPT_NAME AS DEPARTMENT
FROM EMPLOYEE E
CROSS JOIN DEPARTMENT D;

-- NATURAL JOIN
SELECT E.EMP_NAME AS NAME, D.DEPT_NAME AS DEPARTMENT
FROM EMPLOYEE E
NATURAL JOIN DEPARTMENT D;

-- USING THE SYNTAX OF AN IMPLICIT INNER JOIN TO ACCOMPLISH A SELF JOIN
SELECT E1.EMP_NAME AS EMPLOYEE, E2.EMP_NAME AS MANAGER
FROM EMPLOYEE E1, EMPLOYEE E2
WHERE E1.MANAGER_ID = E2.EMP_ID;

-- FIND THE DEPARTMENT WITH THE HIGHEST PAID EMPLOYEE
SELECT D.*
FROM DEPARTMENT D 
JOIN EMPLOYEE E
ON E.DEPT_ID=D.DEPT_ID
WHERE E.MONTHLY_SALARY = 
    (SELECT MAX(MONTHLY_SALARY)
    FROM EMPLOYEE);

SELECT D.DEPT_NAME AS DEPARTMENT, SUM(E.MONTHLY_SALARY) AS TOTAL
FROM DEPARTMENT D
JOIN EMPLOYEE E 
ON D.DEPT_ID = E.DEPT_ID
GROUP BY D.DEPT_NAME;


--------------------------
-- CREATING A VIEW
--------------------------
-- view is a virtual table based on a result set of a SQL statement

CREATE VIEW DEPARTMENT_SPENDING AS 
SELECT D.DEPT_NAME AS DEPARTMENT, SUM(E.MONTHLY_SALARY) AS TOTAL
FROM DEPARTMENT D
JOIN EMPLOYEE E 
ON D.DEPT_ID = E.DEPT_ID
GROUP BY D.DEPT_NAME;

SELECT * 
FROM DEPARTMENT_SPENDING;

UPDATE EMPLOYEE
SET MONTHLY_SALARY = 4500
WHERE EMP_ID = 10;

COMMIT;

