--2.1 a
SELECT *
FROM EMPLOYEE;
--2.1 b
SELECT *
FROM EMPLOYEE
WHERE EMPLOYEE.LASTNAME = 'King';
--2.1 c
SELECT *
FROM EMPLOYEE
WHERE EMPLOYEE.FIRSTNAME = 'Andrew'
UNION
SELECT *
FROM EMPLOYEE
WHERE EMPLOYEE.REPORTSTO = null;
--2.1 d
SELECT *
FROM ALBUM 
ORDER BY TITLE DESC;
--2.1 e
SELECT FIRSTNAME
FROM CUSTOMER
ORDER BY CITY ASC;
--2.1 f
SELECT *
FROM INVOICE
WHERE INVOICE.BILLINGADDRESS LIKE 'T%';

--2.2 a
SELECT *
FROM GENRE;
INSERT INTO GENRE VALUES(26,'Movies');
INSERT INTO GENRE VALUES(27,'Horror');
--2.2 b
INSERT INTO EMPLOYEE VALUES(9,'Fragoso','Jesus','Assistant General Manger',1, '27-MAY-97', '06-MAR-06','143 Rocky Ave.','Edmonton','AB','Canada','78041','+1 (956)220-6607','(956)220-4401','tony@chinookcorp.com');
INSERT INTO EMPLOYEE VALUES(10,'Lucas','Bob','Janitor',2, '02-DEC-90', '20-NOV-02','103 Hillside St.','Edmonton','AB','Canada','78041','+1 (956)220-6607','(956)220-4401','tony@chinookcorp.com');
--2.2c
INSERT INTO CUSTOMER VALUES(60,'Jesus','Fragoso',null, '105 Fairway Lane','Arlington','TX','USA','78943','+1 (956) 220-6607','+1 (956) 220-6607','tony123@gmail.com',null);
INSERT INTO CUSTOMER VALUES(61,'Robert','Johnson','Disney', '145 Cracker Lane','Orlando','FL','USA','7003','+1 (956) 770-8907','+1 (956) 770-8907','123@disneymail.com',null);

--2.3a
UPDATE CUSTOMER 
SET FIRSTNAME = 'Robert',
LASTNAME = 'Walter'
WHERE FIRSTNAME = 'Aaron'
AND LASTNAME = 'Mitchell';
2.3b
UPDATE ARTIST 
SET NAME = 'CCR'
WHERE NAME = 'Creedence Clearwater Revival';

--3.1a
SELECT CUSTOMER.FIRSTNAME,CUSTOMER.LASTNAME, INVOICE.INVOICEID
FROM CUSTOMER
JOIN INVOICE
ON CUSTOMER.CUSTOMERID =INVOICE.CUSTOMERID;
--3.2a
SELECT CUSTOMER.CUSTOMERID,CUSTOMER.FIRSTNAME,CUSTOMER.LASTNAME,INVOICE.INVOICEID,INVOICE.TOTAL
FROM CUSTOMER
FULL JOIN INVOICE
ON CUSTOMER.CUSTOMERID = INVOICE.CUSTOMERID;
--3.3a
SELECT ALBUM.TITLE, ARTIST.NAME 
FROM ALBUM
RIGHT JOIN ARTIST
ON ARTIST.ARTISTID = ALBUM.ARTISTID;
--3.4
SELECT *
FROM ALBUM 
CROSS JOIN ARTIST 
ORDER BY ARTIST.NAME ASC;
--3.5
SELECT E1.EMP_NAME AS EMPLOYEE, E2.EMP_NAME AS MANAGER
FROM EMPLOYEE E1, EMPLOYEE E2
WHERE E1.MANAGER_ID = E2.EMP_ID;

SET SERVEROUTPUT ON;
4.1

 