
/* - Create the tables - */

CREATE TABLE EMPLOYEE(
    EMPLOYEE_ID NUMBER NOT NULL,
    FIRST_NAME VARCHAR2(60) NOT NULL,
    LAST_NAME VARCHAR2(60) NOT NULL,
    TITLE VARCHAR2(60) NOT NULL,
    MANAGER_ID NUMBER,
    EMAIL VARCHAR2(60) NOT NULL,
    PHONE VARCHAR2(20) NOT NULL,
    PASS_HASH RAW(100) NOT NULL,
    PASS_SALT RAW(100) NOT NULL,
    HIRE_DATE DATE NOT NULL,
    ADDRESS VARCHAR2(60) NOT NULL,
    CITY VARCHAR2(60) NOT NULL,
    STATE VARCHAR2(60),
    COUNTRY VARCHAR2(60) NOT NULL,
    POSTAL_CODE VARCHAR2(20) NOT NULL,
    CONSTRAINT PK_EMPLOYEE PRIMARY KEY (EMPLOYEE_ID)
);

CREATE TABLE REIMBURSEMENT_REQUEST(
    REQUEST_ID NUMBER NOT NULL,
    EMPLOYEE_ID NUMBER NOT NULL,
    AMOUNT NUMBER NOT NULL,
    DATE_REQUESTED DATE NOT NULL,
    MANAGER_ID NUMBER,
    WAS_APPROVED NUMBER CHECK(WAS_APPROVED = 1 OR WAS_APPROVED = 0),
    CONSTRAINT PK_REQUEST PRIMARY KEY (REQUEST_ID)
);


/* - Create Additional Constraints - */

ALTER TABLE EMPLOYEE
    ADD CONSTRAINT FK_EMPLOYEE_MANAGER
    FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEE (EMPLOYEE_ID);

ALTER TABLE REIMBURSEMENT_REQUEST
    ADD CONSTRAINT FK_REQUEST_EID
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE (EMPLOYEE_ID);

ALTER TABLE REIMBURSEMENT_REQUEST
    ADD CONSTRAINT FK_REQUEST_MID
    FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEE (EMPLOYEE_ID);
/








