
ALTER TABLE EMPLOYEE
    DROP CONSTRAINT FK_EMPLOYEE_MANAGER;

ALTER TABLE REIMBURSEMENT_REQUEST
    DROP CONSTRAINT FK_REQUEST_EID;

ALTER TABLE REIMBURSEMENT_REQUEST
    DROP CONSTRAINT FK_REQUEST_MID;
    

DROP TABLE EMPLOYEE;
DROP TABLE REIMBURSEMENT_REQUEST;
/