CREATE TABLE LOGIN(
USERNAME VARCHAR2(50) NOT NULL,
PASSWORD VARCHAR2(50) NOT NULL,
CREATE_DATE DATE NOT NULL,
EMP_ID NUMBER(15) NOT NULL,
CONSTRAINT USERNAME_PK PRIMARY KEY (USERNAME));


CREATE TABLE EMPLOYEE(
EMP_ID NUMBER(15) NOT NULL,
FIRSTNAME VARCHAR2(50),
LASTNAME VARCHAR2(50),
EMAIL VARCHAR2(50),
BIRTHDATE DATE,
CONSTRAINT EMP_ID_PK PRIMARY KEY (EMP_ID));

ALTER TABLE LOGIN 
ADD CONSTRAINT EMP_ID_FK 
FOREIGN KEY (EMP_ID)
REFERENCES EMPLOYEE(EMP_ID);

INSERT INTO LOGIN VALUES ('admin', 'root', '19-JUN-19', 0);
INSERT INTO EMPLOYEE VALUES (1, 'George', 'Newman', 'gnewman401@gmail.com', '21-JUL-89');

ALTER TABLE EMPLOYEE
ADD MANAGER NUMBER(15);

ALTER TABLE EMPLOYEE
ADD POSITION VARCHAR2(15);

ALTER TABLE EMPLOYEE
MODIFY POSITION VARCHAR2(15) NOT NULL;

INSERT INTO EMPLOYEE VALUES (2, 'Jack', 'Cross', 'jcross@gmail.com', '19-NOV-82', 1, 'Janitor');
INSERT INTO LOGIN VALUES ('jcross', 'password', '22-JUL-89', 2);


CREATE TABLE REIMBURSE(
REM_ID NUMBER (15) NOT NULL,
DESCRIPTION VARCHAR2(255),
AMOUNT NUMBER(9,2) NOT NULL,
ISSUE_DATE DATE NOT NULL,
FULFILL_DATE DATE,
STATUS VARCHAR2(15)
);

ALTER TABLE REIMBURSE
ADD CONSTRAINT REM_ID_PK PRIMARY KEY (REM_ID);

ALTER TABLE REIMBURSE 
ADD (MAN_ID NUMBER(15), EMP_ID NUMBER(15) NOT NULL);

ALTER TABLE REIMBURSE
ADD CONSTRAINT EMP_ID_R_FK 
FOREIGN KEY (EMP_ID)
REFERENCES EMPLOYEE(EMP_ID);

ALTER TABLE LOGIN
ADD USER_ROLE VARCHAR2(15);

INSERT INTO REIMBURSE (REM_ID, DESCRIPTION, AMOUNT, ISSUE_DATE, STATUS, EMP_ID) VALUES (1, 'Gas for California Trip', 650.00, '13-JAN-18', 'Pending', 2);



---DELETE LOGIN PROCEDURE
CREATE OR REPLACE PROCEDURE DEL_LOGIN (
    USRNM IN LOGIN.USERNAME%TYPE)
AS
BEGIN
    DELETE FROM LOGIN WHERE USRNM = USERNAME;
    COMMIT;
END;

DECLARE
    USRNM LOGIN.USERNAME%TYPE;
    
BEGIN
    USRNM := 'baby';
    DEL_LOGIN(USRNM);
END;


CREATE OR REPLACE PROCEDURE UPD_LOGIN (
    USRNM IN LOGIN.USERNAME%TYPE,
    PSSWD IN LOGIN.PASSWORD%TYPE,
    C_DATE IN LOGIN.CREATE_DATE%TYPE,
    U_ROLE IN LOGIN.USER_ROLE%TYPE)
AS
BEGIN
    UPDATE LOGIN 
    SET USERNAME = USRNM, PASSWORD = PSSWD,
        CREATE_DATE = C_DATE, USER_ROLE = U_ROLE   
    WHERE USRNM = USERNAME;
    COMMIT;
END;

DECLARE
    USRNM LOGIN.USERNAME%TYPE;
    PSSWD LOGIN.PASSWORD%TYPE;
    C_DATE LOGIN.CREATE_DATE%TYPE;
    U_ROLE LOGIN.USER_ROLE%TYPE;
    
BEGIN
    USRNM := 'jcross';
    PSSWD := 'password2';
    C_DATE := '24-AUG-19';
    U_ROLE := 'not user';
    UPD_LOGIN(USRNM, PSSWD, C_DATE,  U_ROLE);
END;



CREATE OR REPLACE PROCEDURE UPD_EMP(
    E_ID IN EMPLOYEE.EMP_ID%TYPE,
    FNAME IN EMPLOYEE.FIRSTNAME%TYPE,
    LNAME IN EMPLOYEE.LASTNAME%TYPE,
    MAIL IN EMPLOYEE.EMAIL%TYPE,
    BDATE IN EMPLOYEE.BIRTHDATE%TYPE,
    MAN IN EMPLOYEE.MANAGER%TYPE,
    POS IN EMPLOYEE.POSITION%TYPE)
AS
BEGIN
    UPDATE EMPLOYEE
    SET FIRSTNAME = FNAME, LASTNAME = LNAME, EMAIL = MAIL,
        BIRTHDATE = BDATE, MANAGER = MAN, POSITION = POS
    WHERE EMP_ID = E_ID;
    COMMIT;
END;





DECLARE
    E_ID EMPLOYEE.EMP_ID%TYPE;
    FNAME EMPLOYEE.FIRSTNAME%TYPE;
    LNAME EMPLOYEE.LASTNAME%TYPE;
    MAIL EMPLOYEE.EMAIL%TYPE;
    BDATE EMPLOYEE.BIRTHDATE%TYPE;
    MAN EMPLOYEE.MANAGER%TYPE;
    POS EMPLOYEE.POSITION%TYPE;
    
BEGIN
    E_ID := 3;
    FNAME := 'Hiker';
    LNAME := 'Jones';
    MAIL := 'hikeymikey@gmail.com';
    BDATE := '12-NOV-90';
    MAN := 2;
    POS := 'Closet Broom';
    UPD_EMP(E_ID, FNAME, LNAME, MAIL, BDATE, MAN, POS);
END;


CREATE OR REPLACE PROCEDURE DEL_EMP(
    E_ID IN EMPLOYEE.EMP_ID%TYPE)
AS
BEGIN
    
    UPDATE LOGIN
    SET EMP_ID = NULL
    WHERE EMP_ID = E_ID;
    
    DELETE FROM EMPLOYEE
    WHERE EMP_ID = E_ID;
    
    COMMIT;
END;    

DECLARE 
    E_ID EMPLOYEE.EMP_ID%TYPE;
BEGIN
    E_ID := 3;
    DEL_EMP(E_ID);
END;    


CREATE OR REPLACE PROCEDURE DEL_REM(
    R_ID IN REIMBURSE.REM_ID%TYPE)
AS
BEGIN
    DELETE FROM REIMBURSE WHERE REM_ID = R_ID;
END;

DECLARE
    R_ID REIMBURSE.REM_ID%TYPE;
BEGIN
    R_ID:= 2;
    DEL_REM(R_ID);
END;





CREATE OR REPLACE PROCEDURE UPD_REM(
    R_ID IN REIMBURSE.REM_ID%TYPE,
    DESCR IN REIMBURSE.DESCRIPTION%TYPE,
    AMNT IN REIMBURSE.AMOUNT%TYPE,
    FDATE IN REIMBURSE.FULFILL_DATE%TYPE,
    STAT IN REIMBURSE.STATUS%TYPE)
AS 
BEGIN
    UPDATE REIMBURSE 
    SET DESCRIPTION = DESCR, AMOUNT = AMNT, FULFILL_DATE = FDATE, 
        STATUS = STAT
    WHERE REM_ID = R_ID; 

    COMMIT;  
END;

DECLARE
    R_ID REIMBURSE.REM_ID%TYPE;
    DESCR REIMBURSE.DESCRIPTION%TYPE;
    AMNT REIMBURSE.AMOUNT%TYPE;
    FDATE REIMBURSE.FULFILL_DATE%TYPE;
    STAT REIMBURSE.STATUS%TYPE;
BEGIN
    R_ID := 13;
    DESCR := 'SHAGGY';
    AMNT := 1823.23;
    FDATE := '24-AUG-00';
    STAT := 'Accepted';
    
    UPD_REM(R_ID, DESCR, AMNT, FDATE, STAT);
END;

CREATE OR REPLACE PROCEDURE INS_REM(
    R_ID IN REIMBURSE.REM_ID%TYPE,
    DESCR IN REIMBURSE.DESCRIPTION%TYPE,
    AMNT IN REIMBURSE.AMOUNT%TYPE,
    IDATE IN REIMBURSE.ISSUE_DATE%TYPE,
    FDATE IN REIMBURSE.FULFILL_DATE%TYPE,
    STATU IN reimburse.status%TYPE,
    M_ID IN reimburse.man_id%TYPE,
    E_ID IN REIMBURSE.EMP_ID%TYPE
)
AS 
BEGIN
    INSERT INTO REIMBURSE VALUES(R_ID, DESCR, AMNT, IDATE, FDATE, STATU, M_ID, E_ID);
    COMMIT;
END;

declare
    R_ID REIMBURSE.REM_ID%TYPE;
    DESCR REIMBURSE.DESCRIPTION%TYPE;
    AMNT REIMBURSE.AMOUNT%TYPE;
    IDATE REIMBURSE.ISSUE_DATE%TYPE;
    FDATE REIMBURSE.FULFILL_DATE%TYPE;
    STATU reimburse.status%TYPE;
    M_ID reimburse.man_id%TYPE;
    E_ID REIMBURSE.EMP_ID%TYPE;
    
BEGIN
    R_ID:=30;
    DESCR:='TESTING THIS PLEASE WORK';
    AMNT :=90.24;
    IDATE := '31-JAN-19';
    FDATE := '4-AUG-19';
    STATU:= 'Pending';
    M_ID:= 3;
    E_ID:= 4;
    
    ins_rem(r_ID, descr, amnt, idate, fdate, statu, m_id, e_Id);
end;
    





