server:
  port: 3333
  
spring:
  application:
    name: customer-service
    
eureka:
  client:
    fetch-registry: true
  instance:
    lease-renewal-interval-in-seconds: 2
    
feign:
  hystrix:
    enabled: true
    
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream