CREATE TABLE products
( product_id numeric(10) not null,
  supplier_id numeric(10) not null,
  CONSTRAINT fk_supplier
    FOREIGN KEY (supplier_id)
    REFERENCES supplier(supplier_id)
);

ALTER TABLE BANK_ACC
ADD CONSTRAINT USER_ID_FK
FOREIGN KEY (USER_ACC_ID)
REFERENCES ACCOUNTS(ACC_ID);

ALTER TABLE ACCOUNTS
ADD CONSTRAINT ACC_ID_U UNIQUE (ACC_ID);

COMMIT;



DELETE FROM BANK_ACC WHERE ACC_NUM = 2 AND USER_ACC_ID = 0;

--Deleting a bank account 
CREATE OR REPLACE PROCEDURE DEL_BANK_ACC (
    A_NUM IN BANK_ACC.ACC_NUM%TYPE,
    U_NUM IN BANK_ACC.USER_ACC_ID%TYPE)
AS
BEGIN
    DELETE FROM BANK_ACC WHERE ACC_NUM = A_NUM AND USER_ACC_ID = U_NUM;
    COMMIT;
END;

DECLARE
    A_NUM BANK_ACC.ACC_NUM%TYPE;
    U_NUM BANK_ACC.USER_ACC_ID%TYPE;
BEGIN
    A_NUM := 4;
    U_NUM := 12;
    DEL_BANK_ACC(A_NUM, U_NUM);
END;




CREATE OR REPLACE PROCEDURE UPD_BANK_ACC(
    NEW_BALANCE IN BANK_ACC.CURRENT_BALANCE%TYPE,
    A_NUM IN BANK_ACC.ACC_NUM%TYPE,
    U_NUM IN BANK_ACC.USER_ACC_ID%TYPE)
AS
BEGIN
    UPDATE BANK_ACC 
    SET CURRENT_BALANCE = NEW_BALANCE
    WHERE ACC_NUM = A_NUM AND USER_ACC_ID = U_NUM;
    COMMIT;
END;

DECLARE
    NEW_BALANCE BANK_ACC.CURRENT_BALANCE%TYPE;
    A_NUM BANK_ACC.ACC_NUM%TYPE;
    U_NUM BANK_ACC.USER_ACC_ID%TYPE;
BEGIN
    NEW_BALANCE := 8000;
    A_NUM := 6;
    U_NUM := 0;
    
    UPD_BANK_ACC(NEW_BALANCE, A_NUM, U_NUM);
END;


    