
ALTER TABLE USER_ACCESS
    DROP CONSTRAINT FK_USER_ACCESS_USERNAME;

ALTER TABLE USER_ACCESS
    DROP CONSTRAINT FK_USER_ACCESS_ACCOUNT_ID;

ALTER TABLE BANK_ACCOUNT
    DROP CONSTRAINT BANK_ACCOUNT_NON_ZERO_BAL;

DROP TABLE BANK_USER;
DROP TABLE BANK_ACCOUNT;
DROP TABLE USER_ACCESS;
DROP TABLE TRANSACTION;
/